name: Node.js CI

on: [push]

jobs:
  test-node:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: Run test with Node.js ${{ matrix.node-version }}
        run: npm run pretest && npm run test-node && npm run posttest
        env:
          CI: true
  # FIXME: fix karma tests
  # test-karma:
  #   needs: [lint]
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 10
  #   strategy:
  #     matrix:
  #       node-version: [20.x]
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #     - run: npm install
  #     - name: Run karma tests
  #       run: npm run pretest && npm run test-karma && npm run posttest
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: Run eslint
        run: npm run lint
